/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/piano/grand_piano_marble.glb -T -t
Files: ./public/piano/grand_piano_marble.glb [89.62MB] > grand_piano_marble-transformed.glb [17.84MB] (80%)
Author: Amatsukast (https://sketchfab.com/Amatsukast)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/grand-piano-marble-8d4142b2c2d94dc7a314764f621845c6
Title: Grand Piano (Marble)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    piano_key_piano_key_black_0: THREE.Mesh;
    piano_key_piano_key_white_0: THREE.Mesh;
    piano_hinji01_piano_hinji01_mt_0: THREE.Mesh;
    piano_hinji02_piano_hinji02_mt_0: THREE.Mesh;
    piano_lid01_piano_lid01_mt_0: THREE.Mesh;
    piano_lid02_piano_lid02_mt_0: THREE.Mesh;
    piano_frame_piano_frame_mt_0: THREE.Mesh;
    pCube29_piano_part01_mt_0: THREE.Mesh;
    piano_plate_piano_plate_mt_0: THREE.Mesh;
    pCube28_piano_part02_mt_0: THREE.Mesh;
    piano_pedal_metal_piano_pedal_metal_mt_0: THREE.Mesh;
    pCube143_piano_part04_mt_0: THREE.Mesh;
    piano_rod01_piano_part03_mt_0: THREE.Mesh;
    piano_rod_metal_piano_stand_metal_mt_0: THREE.Mesh;
    piano_stand_piano_stand_mt_0: THREE.Mesh;
    pPlane8_piano_part05_mt_0: THREE.Mesh;
    pPlane9_piano_part06_mt_0: THREE.Mesh;
    pCylinder146_piano_part07_mt_0: THREE.Mesh;
    pCube110_piano_part08_mt_0: THREE.Mesh;
    piano_leg_wood_piano_leg01_wood_mt_0: THREE.Mesh;
    piano_leg_roller_piano_leg01_roller_mt_0: THREE.Mesh;
    chair_wood_chair_wood_mt_0: THREE.Mesh;
    chair_leather_chair_leather_mt_0: THREE.Mesh;
  };
  materials: {
    piano_key_black: THREE.MeshStandardMaterial;
    piano_key_white: THREE.MeshStandardMaterial;
    piano_hinji01_mt: THREE.MeshStandardMaterial;
    piano_hinji02_mt: THREE.MeshStandardMaterial;
    piano_lid01_mt: THREE.MeshStandardMaterial;
    piano_lid02_mt: THREE.MeshStandardMaterial;
    piano_frame_mt: THREE.MeshStandardMaterial;
    piano_part01_mt: THREE.MeshStandardMaterial;
    piano_plate_mt: THREE.MeshStandardMaterial;
    piano_part02_mt: THREE.MeshStandardMaterial;
    piano_pedal_metal_mt: THREE.MeshStandardMaterial;
    piano_part04_mt: THREE.MeshStandardMaterial;
    piano_part03_mt: THREE.MeshStandardMaterial;
    piano_stand_metal_mt: THREE.MeshStandardMaterial;
    piano_stand_mt: THREE.MeshStandardMaterial;
    piano_part05_mt: THREE.MeshStandardMaterial;
    piano_part06_mt: THREE.MeshStandardMaterial;
    piano_part07_mt: THREE.MeshStandardMaterial;
    piano_part08_mt: THREE.MeshStandardMaterial;
    piano_leg01_wood_mt: THREE.MeshStandardMaterial;
    piano_leg01_roller_mt: THREE.MeshStandardMaterial;
    chair_wood_mt: THREE.MeshStandardMaterial;
    chair_leather_mt: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function GrandPiano(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./piano/grand_piano_marble-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.piano_key_piano_key_black_0.geometry}
        material={materials.piano_key_black}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_key_piano_key_white_0.geometry}
        material={materials.piano_key_white}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_hinji01_piano_hinji01_mt_0.geometry}
        material={materials.piano_hinji01_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_hinji02_piano_hinji02_mt_0.geometry}
        material={materials.piano_hinji02_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_lid01_piano_lid01_mt_0.geometry}
        material={materials.piano_lid01_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_lid02_piano_lid02_mt_0.geometry}
        material={materials.piano_lid02_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_frame_piano_frame_mt_0.geometry}
        material={materials.piano_frame_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pCube29_piano_part01_mt_0.geometry}
        material={materials.piano_part01_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_plate_piano_plate_mt_0.geometry}
        material={materials.piano_plate_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pCube28_piano_part02_mt_0.geometry}
        material={materials.piano_part02_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_pedal_metal_piano_pedal_metal_mt_0.geometry}
        material={materials.piano_pedal_metal_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pCube143_piano_part04_mt_0.geometry}
        material={materials.piano_part04_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_rod01_piano_part03_mt_0.geometry}
        material={materials.piano_part03_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_rod_metal_piano_stand_metal_mt_0.geometry}
        material={materials.piano_stand_metal_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_stand_piano_stand_mt_0.geometry}
        material={materials.piano_stand_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pPlane8_piano_part05_mt_0.geometry}
        material={materials.piano_part05_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pPlane9_piano_part06_mt_0.geometry}
        material={materials.piano_part06_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pCylinder146_piano_part07_mt_0.geometry}
        material={materials.piano_part07_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.pCube110_piano_part08_mt_0.geometry}
        material={materials.piano_part08_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_leg_wood_piano_leg01_wood_mt_0.geometry}
        material={materials.piano_leg01_wood_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.piano_leg_roller_piano_leg01_roller_mt_0.geometry}
        material={materials.piano_leg01_roller_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.chair_wood_chair_wood_mt_0.geometry}
        material={materials.chair_wood_mt}
        scale={50}
      />
      <mesh
        geometry={nodes.chair_leather_chair_leather_mt_0.geometry}
        material={materials.chair_leather_mt}
        scale={50}
      />
    </group>
  );
}

useGLTF.preload("/grand_piano_marble-transformed.glb");
